git clone https://github.com/greenelab/TDM
git clone https://github.com/greenelab/TDM.wiki.git
git clone https://github.com/greenelab/greedy-geneset-selection
git clone https://github.com/greenelab/greedy-geneset-selection.wiki.git
git clone https://github.com/greenelab/siRNA-Community-Enrichment
git clone https://github.com/greenelab/siRNA-Community-Enrichment.wiki.git
git clone https://github.com/greenelab/TDMresults
git clone https://github.com/greenelab/TDMresults.wiki.git
git clone https://github.com/greenelab/hgsc_subtypes
git clone https://github.com/greenelab/hgsc_subtypes.wiki.git
git clone https://github.com/greenelab/adage
git clone https://github.com/greenelab/adage.wiki.git
git clone https://github.com/greenelab/adni-netwas
git clone https://github.com/greenelab/adni-netwas.wiki.git
git clone https://github.com/greenelab/DAPS
git clone https://github.com/greenelab/DAPS.wiki.git
git clone https://github.com/greenelab/DAPS_private
git clone https://github.com/greenelab/DAPS_private.wiki.git
git clone https://github.com/greenelab/gcb535challenge
git clone https://github.com/greenelab/gcb535challenge.wiki.git
git clone https://github.com/greenelab/continuous_analysis
git clone https://github.com/greenelab/continuous_analysis.wiki.git
git clone https://github.com/greenelab/PAINT-prelim
git clone https://github.com/greenelab/PAINT-prelim.wiki.git
git clone https://github.com/greenelab/GEA_Community_Detection
git clone https://github.com/greenelab/GEA_Community_Detection.wiki.git
git clone https://github.com/greenelab/GCB535
git clone https://github.com/greenelab/GCB535.wiki.git
git clone https://github.com/greenelab/generative_adversarial_networks
git clone https://github.com/greenelab/generative_adversarial_networks.wiki.git
git clone https://github.com/greenelab/GCB535-Keys
git clone https://github.com/greenelab/GCB535-Keys.wiki.git
git clone https://github.com/greenelab/model-free-data
git clone https://github.com/greenelab/model-free-data.wiki.git
git clone https://github.com/greenelab/connectivity-search-analyses
git clone https://github.com/greenelab/connectivity-search-analyses.wiki.git
git clone https://github.com/greenelab/nf1_inactivation
git clone https://github.com/greenelab/nf1_inactivation.wiki.git
git clone https://github.com/greenelab/hetontology
git clone https://github.com/greenelab/hetontology.wiki.git
git clone https://github.com/greenelab/continuous_analysis_rnaseq
git clone https://github.com/greenelab/continuous_analysis_rnaseq.wiki.git
git clone https://github.com/greenelab/RNAseq_titration_results
git clone https://github.com/greenelab/RNAseq_titration_results.wiki.git
git clone https://github.com/greenelab/continuous_analysis_phylo
git clone https://github.com/greenelab/continuous_analysis_phylo.wiki.git
git clone https://github.com/greenelab/staNMF
git clone https://github.com/greenelab/staNMF.wiki.git
git clone https://github.com/greenelab/deep-review
git clone https://github.com/greenelab/deep-review.wiki.git
git clone https://github.com/greenelab/continuous_analysis_brainarray
git clone https://github.com/greenelab/continuous_analysis_brainarray.wiki.git
git clone https://github.com/greenelab/tad_pathways
git clone https://github.com/greenelab/tad_pathways.wiki.git
git clone https://github.com/greenelab/GBM_immune_profiles
git clone https://github.com/greenelab/GBM_immune_profiles.wiki.git
git clone https://github.com/greenelab/pdx_exomeseq
git clone https://github.com/greenelab/pdx_exomeseq.wiki.git
git clone https://github.com/greenelab/old-adage-server
git clone https://github.com/greenelab/old-adage-server.wiki.git
git clone https://github.com/greenelab/pancancer
git clone https://github.com/greenelab/pancancer.wiki.git
git clone https://github.com/greenelab/MGN-Subtypes
git clone https://github.com/greenelab/MGN-Subtypes.wiki.git
git clone https://github.com/greenelab/AML-Protein-Histone-Correlations
git clone https://github.com/greenelab/AML-Protein-Histone-Correlations.wiki.git
git clone https://github.com/greenelab/ADAGEpath
git clone https://github.com/greenelab/ADAGEpath.wiki.git
git clone https://github.com/greenelab/old-adage-deploy
git clone https://github.com/greenelab/old-adage-deploy.wiki.git
git clone https://github.com/greenelab/irv
git clone https://github.com/greenelab/irv.wiki.git
git clone https://github.com/greenelab/gbm_immune_validation
git clone https://github.com/greenelab/gbm_immune_validation.wiki.git
git clone https://github.com/greenelab/scrum
git clone https://github.com/greenelab/scrum.wiki.git
git clone https://github.com/greenelab/Vasculitis-Analysis
git clone https://github.com/greenelab/Vasculitis-Analysis.wiki.git
git clone https://github.com/greenelab/aaces_ovarian
git clone https://github.com/greenelab/aaces_ovarian.wiki.git
git clone https://github.com/greenelab/aaces_ovarian_data
git clone https://github.com/greenelab/aaces_ovarian_data.wiki.git
git clone https://github.com/greenelab/computational-reagents
git clone https://github.com/greenelab/computational-reagents.wiki.git
git clone https://github.com/greenelab/chronobiome
git clone https://github.com/greenelab/chronobiome.wiki.git
git clone https://github.com/greenelab/snorkeling
git clone https://github.com/greenelab/snorkeling.wiki.git
git clone https://github.com/greenelab/tad_pathways_pipeline
git clone https://github.com/greenelab/tad_pathways_pipeline.wiki.git
git clone https://github.com/greenelab/pubtator
git clone https://github.com/greenelab/pubtator.wiki.git
git clone https://github.com/greenelab/scihub
git clone https://github.com/greenelab/scihub.wiki.git
git clone https://github.com/greenelab/crossref
git clone https://github.com/greenelab/crossref.wiki.git
git clone https://github.com/greenelab/SPRINT_gan
git clone https://github.com/greenelab/SPRINT_gan.wiki.git
git clone https://github.com/greenelab/SignatureAnalysis-CaseStudy
git clone https://github.com/greenelab/SignatureAnalysis-CaseStudy.wiki.git
git clone https://github.com/greenelab/bioconductor-scraper
git clone https://github.com/greenelab/bioconductor-scraper.wiki.git
git clone https://github.com/greenelab/PathCORE-T
git clone https://github.com/greenelab/PathCORE-T.wiki.git
git clone https://github.com/greenelab/PathCORE-T-analysis
git clone https://github.com/greenelab/PathCORE-T-analysis.wiki.git
git clone https://github.com/greenelab/scrumlord
git clone https://github.com/greenelab/scrumlord.wiki.git
git clone https://github.com/greenelab/scihub-manuscript
git clone https://github.com/greenelab/scihub-manuscript.wiki.git
git clone https://github.com/greenelab/tybalt
git clone https://github.com/greenelab/tybalt.wiki.git
git clone https://github.com/greenelab/django-genes
git clone https://github.com/greenelab/django-genes.wiki.git
git clone https://github.com/greenelab/django-organisms
git clone https://github.com/greenelab/django-organisms.wiki.git
git clone https://github.com/greenelab/meta-review
git clone https://github.com/greenelab/meta-review.wiki.git
git clone https://github.com/greenelab/czi-rfa
git clone https://github.com/greenelab/czi-rfa.wiki.git
git clone https://github.com/greenelab/tribe-client
git clone https://github.com/greenelab/tribe-client.wiki.git
git clone https://github.com/greenelab/annotation-refinery
git clone https://github.com/greenelab/annotation-refinery.wiki.git
git clone https://github.com/greenelab/tribe
git clone https://github.com/greenelab/tribe.wiki.git
git clone https://github.com/greenelab/opencitations
git clone https://github.com/greenelab/opencitations.wiki.git
git clone https://github.com/greenelab/BRCA-degs
git clone https://github.com/greenelab/BRCA-degs.wiki.git
git clone https://github.com/greenelab/cfn-template
git clone https://github.com/greenelab/cfn-template.wiki.git
git clone https://github.com/greenelab/scihub-browser-data
git clone https://github.com/greenelab/scihub-browser-data.wiki.git
git clone https://github.com/greenelab/library-access
git clone https://github.com/greenelab/library-access.wiki.git
git clone https://github.com/greenelab/tribe-ec2-deploy
git clone https://github.com/greenelab/tribe-ec2-deploy.wiki.git
git clone https://github.com/greenelab/rheum-plier-data
git clone https://github.com/greenelab/rheum-plier-data.wiki.git
git clone https://github.com/greenelab/onboarding
git clone https://github.com/greenelab/onboarding.wiki.git
git clone https://github.com/greenelab/manufund-2018
git clone https://github.com/greenelab/manufund-2018.wiki.git
git clone https://github.com/greenelab/czi-cancer-data
git clone https://github.com/greenelab/czi-cancer-data.wiki.git
git clone https://github.com/greenelab/GTEx_VAE
git clone https://github.com/greenelab/GTEx_VAE.wiki.git
git clone https://github.com/greenelab/sm-theme
git clone https://github.com/greenelab/sm-theme.wiki.git
git clone https://github.com/greenelab/czi-hca-report
git clone https://github.com/greenelab/czi-hca-report.wiki.git
git clone https://github.com/greenelab/BioBombe
git clone https://github.com/greenelab/BioBombe.wiki.git
git clone https://github.com/greenelab/multi-plier
git clone https://github.com/greenelab/multi-plier.wiki.git
git clone https://github.com/greenelab/CZI-Latent-Assessment
git clone https://github.com/greenelab/CZI-Latent-Assessment.wiki.git
git clone https://github.com/greenelab/multiple-myeloma-classifier
git clone https://github.com/greenelab/multiple-myeloma-classifier.wiki.git
git clone https://github.com/greenelab/shared-latent-space
git clone https://github.com/greenelab/shared-latent-space.wiki.git
git clone https://github.com/greenelab/Pseudomonas_latent_spaces
git clone https://github.com/greenelab/Pseudomonas_latent_spaces.wiki.git
git clone https://github.com/greenelab/tadpole
git clone https://github.com/greenelab/tadpole.wiki.git
git clone https://github.com/greenelab/cimr
git clone https://github.com/greenelab/cimr.wiki.git
git clone https://github.com/greenelab/netwas_rebooted
git clone https://github.com/greenelab/netwas_rebooted.wiki.git
git clone https://github.com/greenelab/czi-seed-rfa
git clone https://github.com/greenelab/czi-seed-rfa.wiki.git
git clone https://github.com/greenelab/beta_VAE
git clone https://github.com/greenelab/beta_VAE.wiki.git
git clone https://github.com/greenelab/connectivity-search-backend
git clone https://github.com/greenelab/connectivity-search-backend.wiki.git
git clone https://github.com/greenelab/LINCS_latent_space
git clone https://github.com/greenelab/LINCS_latent_space.wiki.git
git clone https://github.com/greenelab/xswap-analysis
git clone https://github.com/greenelab/xswap-manuscript
git clone https://github.com/greenelab/greenblack
git clone https://github.com/greenelab/greenblack.wiki.git
git clone https://github.com/greenelab/connectivity-search-frontend
git clone https://github.com/greenelab/connectivity-search-frontend.wiki.git
git clone https://github.com/greenelab/cimr-d
git clone https://github.com/greenelab/cimr-d.wiki.git
git clone https://github.com/greenelab/assets
git clone https://github.com/greenelab/cycleGAN_gene_expression
git clone https://github.com/greenelab/cycleGAN_gene_expression.wiki.git
git clone https://github.com/greenelab/public-keys
git clone https://github.com/greenelab/public-keys.wiki.git
git clone https://github.com/greenelab/simulate-expression-compendia
git clone https://github.com/greenelab/simulate-expression-compendia.wiki.git
git clone https://github.com/greenelab/third_rotation_content
git clone https://github.com/greenelab/third_rotation_content.wiki.git
git clone https://github.com/greenelab/text_mined_hetnet_manuscript
git clone https://github.com/greenelab/text_mined_hetnet_manuscript.wiki.git
git clone https://github.com/greenelab/readables
git clone https://github.com/greenelab/readables.wiki.git
git clone https://github.com/greenelab/greenelabbot
git clone https://github.com/greenelab/greenelabbot.wiki.git
git clone https://github.com/greenelab/funds
git clone https://github.com/greenelab/funds.wiki.git
git clone https://github.com/greenelab/brd-net
git clone https://github.com/greenelab/brd-net.wiki.git
git clone https://github.com/greenelab/netscape
git clone https://github.com/greenelab/netscape.wiki.git
git clone https://github.com/greenelab/knowledge-graph-review
git clone https://github.com/greenelab/knowledge-graph-review.wiki.git
git clone https://github.com/greenelab/sc-cancer-hgsc
git clone https://github.com/greenelab/sc-cancer-hgsc.wiki.git
git clone https://github.com/greenelab/biopriors-review
git clone https://github.com/greenelab/biopriors-review.wiki.git
git clone https://github.com/greenelab/adage-backend
git clone https://github.com/greenelab/adage-backend.wiki.git
git clone https://github.com/greenelab/scihub-manuscript-es
git clone https://github.com/greenelab/scihub-manuscript-es.wiki.git
git clone https://github.com/greenelab/iscb-diversity
git clone https://github.com/greenelab/iscb-diversity.wiki.git
git clone https://github.com/greenelab/adage-frontend
git clone https://github.com/greenelab/adage-frontend.wiki.git
git clone https://github.com/greenelab/whistl
git clone https://github.com/greenelab/whistl.wiki.git
git clone https://github.com/greenelab/brand
git clone https://github.com/greenelab/brand.wiki.git
git clone https://github.com/greenelab/connectivity-search-manuscript
git clone https://github.com/greenelab/connectivity-search-manuscript.wiki.git
git clone https://github.com/greenelab/hgsc_characterization
git clone https://github.com/greenelab/hgsc_characterization.wiki.git
git clone https://github.com/greenelab/iscb-diversity-manuscript
git clone https://github.com/greenelab/iscb-diversity-manuscript.wiki.git
git clone https://github.com/greenelab/wiki-nationality-estimate
git clone https://github.com/greenelab/wiki-nationality-estimate.wiki.git
git clone https://github.com/greenelab/annorxiver
git clone https://github.com/greenelab/annorxiver.wiki.git
git clone https://github.com/greenelab/mito-filtering
git clone https://github.com/greenelab/mito-filtering.wiki.git
git clone https://github.com/greenelab/hclust
git clone https://github.com/greenelab/hclust.wiki.git
git clone https://github.com/greenelab/covid19-review
git clone https://github.com/greenelab/covid19-review.wiki.git
git clone https://github.com/greenelab/eslint-config-greenelab
git clone https://github.com/greenelab/eslint-config-greenelab.wiki.git
git clone https://github.com/greenelab/prettier-config-greenelab
git clone https://github.com/greenelab/prettier-config-greenelab.wiki.git
git clone https://github.com/greenelab/core-accessory-interactome
git clone https://github.com/greenelab/core-accessory-interactome.wiki.git
git clone https://github.com/greenelab/circadian-clock-modulators
git clone https://github.com/greenelab/circadian-clock-modulators.wiki.git
git clone https://github.com/greenelab/annorxiver_manuscript
git clone https://github.com/greenelab/annorxiver_manuscript.wiki.git
git clone https://github.com/greenelab/interviews
git clone https://github.com/greenelab/interviews.wiki.git
git clone https://github.com/greenelab/saged
git clone https://github.com/greenelab/saged.wiki.git
git clone https://github.com/greenelab/generic-expression-patterns
git clone https://github.com/greenelab/generic-expression-patterns.wiki.git
git clone https://github.com/greenelab/ponyo
git clone https://github.com/greenelab/ponyo.wiki.git
git clone https://github.com/greenelab/preprint-similarity-search
git clone https://github.com/greenelab/preprint-similarity-search.wiki.git
git clone https://github.com/greenelab/phenoplier_manuscript
git clone https://github.com/greenelab/phenoplier_manuscript.wiki.git
git clone https://github.com/greenelab/phenoplier
git clone https://github.com/greenelab/phenoplier.wiki.git
git clone https://github.com/greenelab/multi-plier_phenomexcan
git clone https://github.com/greenelab/multi-plier_phenomexcan.wiki.git
git clone https://github.com/greenelab/compbio-edi
git clone https://github.com/greenelab/compbio-edi.wiki.git
git clone https://github.com/greenelab/pancancer-evaluation
git clone https://github.com/greenelab/pancancer-evaluation.wiki.git
git clone https://github.com/greenelab/archs4-plier
git clone https://github.com/greenelab/archs4-plier.wiki.git
git clone https://github.com/greenelab/lab-website-template
git clone https://github.com/greenelab/lab-website-template.wiki.git
git clone https://github.com/greenelab/biovectors
git clone https://github.com/greenelab/biovectors.wiki.git
git clone https://github.com/greenelab/annorxiver-journal-recommender
git clone https://github.com/greenelab/annorxiver-journal-recommender.wiki.git
git clone https://github.com/greenelab/kegg_geneset
git clone https://github.com/greenelab/kegg_geneset.wiki.git
git clone https://github.com/greenelab/mpmp
git clone https://github.com/greenelab/mpmp.wiki.git
git clone https://github.com/greenelab/nature_news_disparities
git clone https://github.com/greenelab/nature_news_disparities.wiki.git
git clone https://github.com/greenelab/disease_ontology_geneset
git clone https://github.com/greenelab/disease_ontology_geneset.wiki.git
git clone https://github.com/greenelab/snorkeling-full-text
git clone https://github.com/greenelab/snorkeling-full-text.wiki.git
git clone https://github.com/greenelab/cu-processes
git clone https://github.com/greenelab/cu-processes.wiki.git
git clone https://github.com/greenelab/wenda_TP53
git clone https://github.com/greenelab/wenda_TP53.wiki.git
git clone https://github.com/greenelab/miQC
git clone https://github.com/greenelab/miQC.wiki.git
git clone https://github.com/greenelab/preprint-bot
git clone https://github.com/greenelab/cnv_analysis_hgsoc
git clone https://github.com/greenelab/cnv_analysis_hgsoc.wiki.git
git clone https://github.com/greenelab/mpmp-manuscript
git clone https://github.com/greenelab/mpmp-manuscript.wiki.git
git clone https://github.com/greenelab/backup
git clone https://github.com/greenelab/backup.wiki.git
git clone https://github.com/greenelab/greenelab.com
git clone https://github.com/greenelab/nature_news_manuscript
git clone https://github.com/greenelab/nature_news_manuscript.wiki.git