name: Archive

on:
  # run once a month
  schedule:
    - cron: "0 0 1 * *"
  # run on manual trigger
  workflow_dispatch:

env:
  FORCE_COLOR: true
  GITHUB_USER: "${{ secrets.GITHUB_USER }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  SOFTWARE_HERITAGE_TOKEN: "${{ secrets.SOFTWARE_HERITAGE_TOKEN }}"

jobs:
  archive:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install packages
        run: npm install

      - name: Run archive
        run: npm run archive
        timeout-minutes: 60
