name: Run Archive

on:
  # once a month
  schedule:
    - cron: "0 0 1 * *"
  # on demand
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
      # secrets to environment variables
    environment: backup
    env:
      SOFTWARE_HERITAGE_TOKEN: ${{ secrets.SOFTWARE_HERITAGE_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install packages
        run: yarn install
      - name: Run archive
        run: yarn archive
